### ISSUE TITLE
Failed at the rubikscube@1.0.0 react-dev script.

### ISSUE THREAD

**Issue by mburakerman** [rogersanick/rubikscubesolver#1]
after `npm install`, i run  `npm run react-dev` and get this error.
[get this error](https://i.hizliresim.com/DDrJ5z.png)

<br>
<br>

> rubikscube@1.0.0 react-dev C:\Users\ZeroPC\Desktop\rubikscubesolver-master
> webpack -d --watch

'webpack' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rubikscube@1.0.0 react-dev: `webpack -d --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rubikscube@1.0.0 react-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ZeroPC\AppData\Roaming\npm-cache\_logs\2018-08-28T12_27_04_561Z-debug.log

**Comment by mburakerman** [comment]
i thought this is could be webpack issue then installed webpack and webpack-cli globally and then get this error;
[after installing webpack globally](https://prnt.sc/knt8rz)

do you have any idea why? 
thank you!

<br>

WARNING in ./client/src/firebaseConfig.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\ZeroPC\Desktop\rubikscubesolver-master\node_modules\babel-loader\lib\index.js??ref--4!C:\Users\ZeroPC\Desktop\rubikscubesolver-master\client\src\firebaseConfig.js
    Used by 1 module(s), i. e.
    C:\Users\ZeroPC\Desktop\rubikscubesolver-master\node_modules\babel-loader\lib\index.js??ref--4!C:\Users\ZeroPC\Desktop\rubikscubesolver-master\client\src\components\login.jsx
* C:\Users\ZeroPC\Desktop\rubikscubesolver-master\node_modules\babel-loader\lib\index.js??ref--4!C:\Users\ZeroPC\Desktop\rubikscubesolver-master\client\src\firebaseconfig.js
    Used by 1 module(s), i. e.
    C:\Users\ZeroPC\Desktop\rubikscubesolver-master\node_modules\babel-loader\lib\index.js??ref--4!C:\Users\ZeroPC\Desktop\rubikscubesolver-master\client\src\components\dashboard.jsx
 @ ./client/src/firebaseConfig.js
 @ ./client/src/components/login.jsx
 @ ./client/src/app.jsx
 @ ./client/src/index.jsx

**Comment by rogersanick** [comment]
Hey mburakerman, thanks for reaching out! Hope I can help. 

Couple of questions:
1. The new error appears to only be a warning, are you still unable to compile?
2. Which OS are you on?
3. JIC - which version of node are you using? (try node -v in the console).

I'm sure we can get this working for you. Here's a [https://github.com/gdi2290/angular-starter/issues/926](link) to an article with some info that might be helpful. Let me know about these questions and I'm happy to help out.
